### ISSUE TITLE
ModuleNotFoundError when importing from aggregatedata.py

### ISSUE THREAD

**Issue by kmunve** [NVE/avalanche_ml#6]
I get the following error when importing fram aggregatedata.py.
My file is in a subfolder of avalanche_ml.

`
ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-3-8aed6d464d6b> in <module>
----> 1 from aggregatedata import ForecastDataset, LabeledData, REG_ENG, CsvMissingError
      2 

~\PycharmProjects\avalanche_ml\aggregatedata.py in <module>
     18 
     19 sys.path.insert(0, "./varsomdata")
---> 20 import setenvironment as se
     21 from varsomdata import getforecastapi as gf
     22 from varsomdata import getvarsompickles as gvp

ModuleNotFoundError: No module named 'setenvironment'
`

**Comment by widforss** [comment]
The problem here is that the script in the subdirectory runs with that directory as working directory. So when `aggregatedata.py` is imported, sys.path looks for `subdir/varsomdata` instead of `varsomdata`. This can be solved by adding the following code to the top of `aggregatedata.py`

```python
import os

os.chdir(os.path.dirname(os.path.abspath(__file__)))
```

**Comment by widforss** [comment]
Verify that #8 works for you and merge.
